on: push

jobs:
  test-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions@checkout-v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install dependencies
        working-directory: web
        run: npm install
      
      - name: Run frontend tests
        working-directory: web
        run: npm test